apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fe90c7gnu-python 
  janus-idp.io/tekton: fe90c7gnu-python
  backstage.io/kubernetes-id: fe90c7gnu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fe90c7gnu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  