apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: fe90c7gnu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fe90c7gnu-python 
  name: fe90c7gnu-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fe90c7gnu-python
    weight: 100 
